### ISSUE TITLE
Error when using with alembic

### ISSUE THREAD

**Issue by geniuslwf** [cloud-utils/sqlalchemy-aurora-data-api#23] opened 2021-03-25 01:10 UTC
2021-03-24T17:46:17.249-07:00	Traceback (most recent call last):
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/aurora_data_api/__init__.py", line 208, in execute
￼
2021-03-24T17:46:17.249-07:00	res = self._client.execute_statement(**execute_statement_args)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/botocore/client.py", line 357, in _api_call
￼
2021-03-24T17:46:17.249-07:00	return self._make_api_call(operation_name, kwargs)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/botocore/client.py", line 676, in _make_api_call
￼
2021-03-24T17:46:17.249-07:00	raise error_class(parsed_response, operation_name)
￼
2021-03-24T17:46:17.249-07:00
￼
Copy
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Database error code: 1146. Message: Table 'truth_team_db.alembic_version' doesn't exist
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the ExecuteStatement operation: Database error code: 1146. Message: Table 'truth_team_db.alembic_version' doesn't exist
￼
2021-03-24T17:46:17.249-07:00	During handling of the above exception, another exception occurred:
￼
2021-03-24T17:46:17.249-07:00	Traceback (most recent call last):
￼
2021-03-24T17:46:17.249-07:00	File "alembic/env.py", line 47, in run_migrations_online
￼
2021-03-24T17:46:17.249-07:00	context.run_migrations()
￼
2021-03-24T17:46:17.249-07:00	File "<string>", line 8, in run_migrations
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/alembic/runtime/environment.py", line 846, in run_migrations
￼
2021-03-24T17:46:17.249-07:00	self.get_context().run_migrations(**kw)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/alembic/runtime/migration.py", line 498, in run_migrations
￼
2021-03-24T17:46:17.249-07:00	heads = self.get_current_heads()
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/alembic/runtime/migration.py", line 435, in get_current_heads
￼
2021-03-24T17:46:17.249-07:00	if not self._has_version_table():
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/alembic/runtime/migration.py", line 448, in _has_version_table
￼
2021-03-24T17:46:17.249-07:00	self.connection, self.version_table, self.version_table_schema
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/alembic/util/sqla_compat.py", line 54, in _connectable_has_table
￼
2021-03-24T17:46:17.249-07:00	connectable, tablename, schemaname
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/dialects/mysql/base.py", line 2482, in has_table
￼
2021-03-24T17:46:17.249-07:00	).execute(st)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/base.py", line 1006, in execute
￼
2021-03-24T17:46:17.249-07:00	return self._execute_text(object_, multiparams, params)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/base.py", line 1181, in _execute_text
￼
2021-03-24T17:46:17.249-07:00	parameters,
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/base.py", line 1318, in _execute_context
￼
2021-03-24T17:46:17.249-07:00	e, statement, parameters, cursor, context
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/base.py", line 1515, in _handle_dbapi_exception
￼
2021-03-24T17:46:17.249-07:00	util.raise_(exc_info[1], with_traceback=exc_info[2])
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/util/compat.py", line 178, in raise_
￼
2021-03-24T17:46:17.249-07:00	raise exception
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/base.py", line 1278, in _execute_context
￼
2021-03-24T17:46:17.249-07:00	cursor, statement, parameters, context
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/sqlalchemy/engine/default.py", line 593, in do_execute
￼
2021-03-24T17:46:17.249-07:00	cursor.execute(statement, parameters)
￼
2021-03-24T17:46:17.249-07:00	File "/var/task/aurora_data_api/__init__.py", line 218, in execute
￼
2021-03-24T17:46:17.249-07:00	raise self._get_database_error(e) from e
￼

**Comment by bruceadams** [comment] 2021-07-19 21:02
I am successfully using [alembic](https://alembic.sqlalchemy.org/) with [sqlalchemy-aurora-data-api](https://github.com/cloud-utils/sqlalchemy-aurora-data-api/).

The error message you shared seems to indicate that [alembic](https://alembic.sqlalchemy.org/) is trying to run a migration on an existing database, but the database does not have the `alembic_version` table that [alembic](https://alembic.sqlalchemy.org/) uses for tracking migration status. I don't think this error is related to [sqlalchemy-aurora-data-api](https://github.com/cloud-utils/sqlalchemy-aurora-data-api/).

**Comment by neilferreira** [comment] 2021-08-04 11:54
What @bruceadams said.  I'm using alembic with this project and it has been working just fine, let us know if your problem persists and I can try and help

**Comment by geniuslwf** [comment] 2021-08-04 16:54
Alembic is supposed to create the alembic_version when it doesn't exist. I've tried to switch to direct db connection and use mysqlclient connector, then it worked just fine.

**Comment by geniuslwf** [comment] 2021-08-04 16:56
I think the real problem is that for connector like mysqlclient, the exception for table doesn't exist is recognized and handled, so that it didn't raise error when checking for table existence. But in aurora-data-api connector, the exception was not recognized, and not handled in the check table existence function inside alembic.

**Comment by bruceadams** [comment] 2021-08-04 17:43
Not recognizing the exception sounds like a good theory.

I run [alembic](https://alembic.sqlalchemy.org/) on empty databases using sqlalchemy-aurora-data-api all the time (every new pull request to our project creates a new database within an existing RDS cluster and runs `alembic upgrade head` to create the schema).

I wonder how [alembic](https://alembic.sqlalchemy.org/) figures out that it needs to create the `alembic_version` table for an empty database, but fails to do so for your database? What's the difference? Maybe [alembic](https://alembic.sqlalchemy.org/) does something like `show tables` to see if there is _anything_ setup in the database? But, when [alembic](https://alembic.sqlalchemy.org/) finds any tables, it takes a different path that is failing.

**Comment by geniuslwf** [comment] 2021-08-04 18:47
The "_has_version_table" in alembic/runtime/migration.py is supposed to return True/False, but raised exception with aurora-data-api. I think that's a good starting point.

Yes, my project didn't create new database, but using a pre-defined one, maybe that's the difference.

**Comment by bruceadams** [comment] 2021-08-04 19:41
[has_table in sqlalchemy/dialects/mysql/base.py](https://github.com/sqlalchemy/sqlalchemy/blob/rel_1_4_22/lib/sqlalchemy/dialects/mysql/base.py#L2883-L2903) changed _a lot_ between v1.3.x and v1.4.x. Any chance you can try using SQLAlchemy v1.4.x? The v1.4 code shouldn't fail with the error you are getting.

**Comment by geniuslwf** [comment] 2021-08-04 20:41
When I reported this issue I was using 1.3.x. I was later switched to 1.4.x after switching to direct db connection. I'll give it a try, thanks!

**Comment by kislyuk** [comment] 2022-01-23 22:11
I am going to close this issue for now since there is no reproduction. If you are still encountering the issue and need help, please attach a complete minimal reproduction.

**Closed by kislyuk** 2022-01-23 22:11 UTC
